apiVersion: v1
kind: Secret
metadata:
  name: container-escape-secrets
type: Opaque
stringData:
  MONGODB_URI: "mongodb://admin:password@mongodb:27017"
  ADMIN_API_KEY: "change-me-admin"
  ANALYST_API_KEY: "change-me-analyst"
  VIEWER_API_KEY: "change-me-viewer"
  SMTP_HOST: "smtp.example.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "smtp-user"
  SMTP_PASSWORD: "smtp-pass"
  SMTP_FROM_EMAIL: "security@example.com"
